In [48]:
import re
import spacy
import pandas as pd
from gensim import corpora
from gensim.models import CoherenceModel
from gensim.models.ldamodel import LdaModel
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from IPython.display import display

In [23]:
# Download VADER lexicon if not already downloaded
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/madhusudhananjeyaram/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [24]:
def load_chat_data(filepath):
    """
    Loads chat data from a text file, skipping bad lines.
    """
    df = pd.read_csv(filepath, header=None, encoding='utf8', on_bad_lines='skip')
    return df

In [25]:
def preprocess_chat_dataframe(df):
    """
    Cleans and structures the chat DataFrame.
    Drops the first row, renames columns, splits chat into time, name, and message.
    Returns the processed DataFrame.
    """
    df = df.drop(0)
    df.columns = ['Date', 'Chat']
    Message = df["Chat"].str.split("-", n=1, expand=True)
    df["Time"] = Message[0]
    Message1 = Message[1].str.split(":", n=1, expand=True)
    df["Name"] = Message1[0]
    df["Chat"] = Message1[1]
    df = df[["Date", "Time", "Name", "Chat"]]
    return df

In [42]:
def tfidf_lda_topic_modeling(df, n_topics=5, n_words=10):
    """
    Assigns a topic_type to each row in the DataFrame using LDA.
    Removes top_words from the output.
    Returns the DataFrame with a topic_type column.
    """
    
    custom_stop_words = list(ENGLISH_STOP_WORDS) + ['hi', 'hello', 'please', 'thanks']
    texts = df['Chat'].astype(str).tolist()
    vectorizer = CountVectorizer(stop_words=custom_stop_words)
    X = vectorizer.fit_transform(texts)
    lda = LatentDirichletAllocation(n_components=n_topics, random_state=42)
    lda.fit(X)

    # Assign topic_type to each row based on the highest topic probability
    topic_assignments = lda.transform(X).argmax(axis=1)
    df = df.copy()
    df['topic_type'] = ['Topic {}'.format(i+1) for i in topic_assignments]
    return df

In [27]:
def append_sentiment_scores(df, text_column='Chat'):
    """
    Appends sentiment scores (neg, neu, pos, compound) to the DataFrame for the specified text column.
    """
    sid = SentimentIntensityAnalyzer()
    sentiments = df[text_column].astype(str).apply(sid.polarity_scores)
    df['neg'] = sentiments.apply(lambda x: x['neg'])
    df['neu'] = sentiments.apply(lambda x: x['neu'])
    df['pos'] = sentiments.apply(lambda x: x['pos'])
    df['compound'] = sentiments.apply(lambda x: x['compound'])
    return df

In [44]:
def count_topic_types(df):
    """
    Counts the number of rows for each topic_type in the DataFrame.
    Returns a Series with topic_type as index and counts as values.
    """
    return df['topic_type'].value_counts()

## 1. Load data from file.

In [28]:
df = load_chat_data("mabel.txt")
print (df)

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

## 2. Preprocess (clean and structure) the chat data.

In [29]:
df = preprocess_chat_dataframe(df)

In [30]:
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [31]:
df = append_sentiment_scores(df)

In [32]:
df

,Date,Time,Name,Chat,neg,neu,pos,compound
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,0.000,1.000,0.000,0.0000
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,0.000,1.000,0.000,0.0000
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,0.000,1.000,0.000,0.0000
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,0.000,0.000,1.000,0.2960
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,0.000,1.000,0.000,0.0000
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,0.000,1.000,0.000,0.0000
7,05/12/19,1:43 pm,AR❤,Yes Mam,0.000,0.270,0.730,0.4019
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,0.000,1.000,0.000,0.0000
9,05/12/19,1:43 pm,AR❤,Yeah mam,0.000,0.312,0.688,0.2960
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,0.000,1.000,0.000,0.0000
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,0.000,0.915,0.085,0.0772
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,0.000,0.761,0.239,0.2960
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,0.000,1.000,0.000,0.0000
14,05/12/19,1:48 pm,Mabel Infoziant,ok,0.000,0.000,1.000,0.2960
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,0.000,0.896,0.104,0.3612
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,0.000,0.609,0.391,0.5423
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,0.000,1.000,0.000,0.0000
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,0.000,1.000,0.000,0.0000
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,0.000,1.000,0.000,0.0000
20,05/12/19,2:06 pm,AR❤,Ok mam,0.000,0.312,0.688,0.2960
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,0.000,1.000,0.000,0.0000
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,0.000,0.838,0.162,0.4019
23,05/12/19,4:48 pm,AR❤,Sure mam.,0.000,0.303,0.697,0.3182
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,0.000,1.000,0.000,0.0000
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,0.000,1.000,0.000,0.0000
26,08/12/19,11:52 pm,AR❤,It's k mam,0.000,1.000,0.000,0.0000
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,0.000,0.775,0.225,0.4404
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,0.000,0.707,0.293,0.1680
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),0.000,1.000,0.000,0.0000
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,0.302,0.698,0.000,-0.0772
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,0.000,1.000,0.000,0.0000
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,0.000,1.000,0.000,0.0000
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,0.000,1.000,0.000,0.0000
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,0.000,0.875,0.125,0.5106
35,09/12/19,12:28 pm,AR❤,You deleted this message,0.000,1.000,0.000,0.0000
36,09/12/19,12:29 pm,AR❤,Do the needful,0.000,1.000,0.000,0.0000
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,0.174,0.736,0.089,-0.2960
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,0.000,0.175,0.825,0.5719
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,0.000,1.000,0.000,0.0000
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,0.000,0.762,0.238,0.3612
41,10/12/19,8:55 am,AR❤,Okay mam,0.000,0.345,0.655,0.2263
42,12/12/19,2:26 pm,Mabel Infoziant,ok,0.000,0.000,1.000,0.2960
43,15/12/19,8:22 pm,AR❤,Mam are u free?,0.000,0.377,0.623,0.5106
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,0.000,1.000,0.000,0.0000
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,0.111,0.619,0.270,0.5574
46,18/12/19,3:09 pm,AR❤,Hi mam,0.000,1.000,0.000,0.0000
47,18/12/19,3:09 pm,AR❤,Any updates mam?,0.000,1.000,0.000,0.0000
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,0.000,1.000,0.000,0.0000
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,0.000,0.741,0.259,0.2732
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,0.000,0.286,0.714,0.3612

## 3. Vectorize text into a document-term matrix.

In [43]:
topics_df = tfidf_lda_topic_modeling(df, n_topics=5, n_words=10)
topics_df

,Date,Time,Name,Chat,neg,neu,pos,compound,topic_type
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,0.000,1.000,0.000,0.0000,Topic 4
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,0.000,1.000,0.000,0.0000,Topic 1
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,0.000,1.000,0.000,0.0000,Topic 4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,0.000,0.000,1.000,0.2960,Topic 5
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,0.000,1.000,0.000,0.0000,Topic 4
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,0.000,1.000,0.000,0.0000,Topic 2
7,05/12/19,1:43 pm,AR❤,Yes Mam,0.000,0.270,0.730,0.4019,Topic 2
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,0.000,1.000,0.000,0.0000,Topic 3
9,05/12/19,1:43 pm,AR❤,Yeah mam,0.000,0.312,0.688,0.2960,Topic 5
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,0.000,1.000,0.000,0.0000,Topic 2
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,0.000,0.915,0.085,0.0772,Topic 2
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,0.000,0.761,0.239,0.2960,Topic 5
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,0.000,1.000,0.000,0.0000,Topic 1
14,05/12/19,1:48 pm,Mabel Infoziant,ok,0.000,0.000,1.000,0.2960,Topic 5
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,0.000,0.896,0.104,0.3612,Topic 3
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,0.000,0.609,0.391,0.5423,Topic 5
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,0.000,1.000,0.000,0.0000,Topic 5
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,0.000,1.000,0.000,0.0000,Topic 2
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,0.000,1.000,0.000,0.0000,Topic 1
20,05/12/19,2:06 pm,AR❤,Ok mam,0.000,0.312,0.688,0.2960,Topic 5
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,0.000,1.000,0.000,0.0000,Topic 5
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,0.000,0.838,0.162,0.4019,Topic 2
23,05/12/19,4:48 pm,AR❤,Sure mam.,0.000,0.303,0.697,0.3182,Topic 5
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,0.000,1.000,0.000,0.0000,Topic 5
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,0.000,1.000,0.000,0.0000,Topic 3
26,08/12/19,11:52 pm,AR❤,It's k mam,0.000,1.000,0.000,0.0000,Topic 5
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,0.000,0.775,0.225,0.4404,Topic 2
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,0.000,0.707,0.293,0.1680,Topic 2
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),0.000,1.000,0.000,0.0000,Topic 2
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,0.302,0.698,0.000,-0.0772,Topic 1
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,0.000,1.000,0.000,0.0000,Topic 2
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,0.000,1.000,0.000,0.0000,Topic 4
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,0.000,1.000,0.000,0.0000,Topic 4
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,0.000,0.875,0.125,0.5106,Topic 5
35,09/12/19,12:28 pm,AR❤,You deleted this message,0.000,1.000,0.000,0.0000,Topic 2
36,09/12/19,12:29 pm,AR❤,Do the needful,0.000,1.000,0.000,0.0000,Topic 1
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,0.174,0.736,0.089,-0.2960,Topic 5
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,0.000,0.175,0.825,0.5719,Topic 5
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,0.000,1.000,0.000,0.0000,Topic 1
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,0.000,0.762,0.238,0.3612,Topic 4
41,10/12/19,8:55 am,AR❤,Okay mam,0.000,0.345,0.655,0.2263,Topic 5
42,12/12/19,2:26 pm,Mabel Infoziant,ok,0.000,0.000,1.000,0.2960,Topic 5
43,15/12/19,8:22 pm,AR❤,Mam are u free?,0.000,0.377,0.623,0.5106,Topic 5
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,0.000,1.000,0.000,0.0000,Topic 4
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,0.111,0.619,0.270,0.5574,Topic 2
46,18/12/19,3:09 pm,AR❤,Hi mam,0.000,1.000,0.000,0.0000,Topic 5
47,18/12/19,3:09 pm,AR❤,Any updates mam?,0.000,1.000,0.000,0.0000,Topic 5
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,0.000,1.000,0.000,0.0000,Topic 3
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,0.000,0.741,0.259,0.2732,Topic 4
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,0.000,0.286,0.714,0.3612,Topic 2

## 4.Display top words for each topic.

In [49]:
topic_counts = count_topic_types(topics_df)
display(topic_counts)

topic_type
Topic 5    19
Topic 2    13
Topic 4     8
Topic 1     6
Topic 3     4
Name: count, dtype: int64